# Generated by Django 3.0.1 on 2021-03-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default-user-img-768x768.jpg', upload_to='users_profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
